version: '3'
services:
  othello_postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=othello
    - POSTGRES_USER=othello
    - POSTGRES_PASSWORD=pwd
    volumes:
    - "othello_pgdata:/var/lib/postgresql/data"
  othello_redis:
    image: redis:latest
    ports:
    - "6379:6379"
volumes:
  othello_pgdata:
